name: driftguard
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  # - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  # - ld_impl_linux-64=2.38
  - libffi=3.4.4
  # - libgcc-ng=11.2.0
  # - libgomp=11.2.0
  # - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1w
  - python=3.10.10
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.15.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - boto3==1.34.142
      - botocore==1.34.142
      - cachetools==5.3.3
      - certifi==2024.7.4
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - dnspython==2.6.1
      - email-validator==2.2.0
      - etils==1.7.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - faker==27.0.0
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - fire==0.6.0
      - flatbuffers
      - fonttools==4.53.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gast
      - google-auth==2.32.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - grpcio==1.64.1
      - gviz-api==1.10.0
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - idna==3.7
      - importlib-resources==6.4.0
      - ipykernel==6.26.0
      - ipython==8.17.2
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jax==0.4.31
      # - jax-cuda12-pjrt==0.4.31
      # - jax-cuda12-plugin==0.4.31
      - jaxlib==0.4.31
      - jedi==0.19.1
      - jinja2==3.1.4
      - jiter==0.5.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kagglehub==0.2.9
      - keras==3.4.1
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - lightning==2.3.3
      - lightning-cloud==0.5.70
      - lightning-sdk==0.1.10
      - lightning-utilities==0.11.3.post0
      - litdata==0.2.13
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-dtypes
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - namex==0.0.8
      - nanoid==2.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook-shim==0.2.4
      - numpy==1.26.4
      # - nvidia-cublas-cu12==12.1.3.1
      # - nvidia-cuda-cupti-cu12==12.1.105
      # - nvidia-cuda-nvcc-cu12==12.6.20
      # - nvidia-cuda-nvrtc-cu12==12.1.105
      # - nvidia-cuda-runtime-cu12==12.1.105
      # - nvidia-cudnn-cu12==9.3.0.75
      # - nvidia-cufft-cu12==11.0.2.54
      # - nvidia-curand-cu12==10.3.2.106
      # - nvidia-cusolver-cu12==11.4.5.107
      # - nvidia-cusparse-cu12==12.1.0.106
      # - nvidia-nccl-cu12==2.19.3
      # - nvidia-nvjitlink-cu12==12.5.82
      # - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - openai==1.41.0
      - opt-einsum==3.3.0
      - optree==0.12.1
      - orbax==0.1.9
      - orbax-checkpoint==0.5.23
      - ordered-set==4.1.0
      - orjson==3.10.6
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.1.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - penzai==0.2.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - pip==24.1.2
      - platformdirs==4.2.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==17.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pygments==2.18.0
      - pyjwt==2.8.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.9
      - pytorch-lightning==2.3.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - referencing==0.35.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.19.0
      - rsa==4.9
      - s3transfer==0.10.2
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - simple-term-menu==1.6.4
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - starlette==0.37.2
      - sympy==1.13.0
      - tensorboard
      - tensorboard-data-server
      - tensorboard-plugin-profile
      - tensorflow
      - tensorflow-io-gcs-filesystem
      - tensorstore
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tomli==2.0.1
      - torch==2.2.1
      - torchmetrics==1.3.1
      - torchvision==0.17.1
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - treescope==0.1.0
      # - triton==2.2.0
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - ujson==5.10.0
      - uri-template==1.3.0
      - urllib3==2.2.2
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - watchfiles==0.22.0
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - yarl==1.9.4
      - zipp==3.19.2

